Web/Controllers/HibernatedController.cs
using Core.Model;
using Core.Persistence;
using Core.Persistence.EntityFramework;
using System.Web.Mvc;

namespace Web.Controllers
{
	public class HibernatedController : Controller
	{
		private readonly IRepository _repository;

		public HibernatedController(NHibernateRepository repository)
		{
			_repository = repository;
		}

		public ActionResult Index()
		{
			return View(_repository.GetAll<User>());
		}

		public ActionResult Create(User user)
		{
			_repository.SaveOrUpdate(user);

			return RedirectToAction("Index");
		}
	}
}

Web/Controllers/HomeController.cs
using Core.Model;
using Core.Persistence;
using System.Web.Mvc;

namespace Web.Controllers
{
	public class HomeController : Controller
	{
		private readonly IRepository _repository;

		public HomeController(IRepository repository)
		{
			_repository = repository;
		}

		public ActionResult Index()
		{
			return View(_repository.GetAll<User>());
		}

		public ActionResult Create(User user)
		{
			_repository.SaveOrUpdate(user);

			return RedirectToAction("Index");
		}
	}
}

Web/Views/Hibernated/Index.cshtml
@model IEnumerable<Core.Model.User>

<h2>Index</h2>

<ul>
	@foreach (var user in Model)
	{
		<li>@user.Name (@user.EmailAddress)</li>
	}
</ul>

@using(Html.BeginForm("Create", "Hibernated", FormMethod.Post))
{
	<input type="text" name="Name" />
	<input type="text" name="EmailAddress" />
	<input type="submit" value="Submit" />
}

Web/Views/Home/Index.cshtml
@model IEnumerable<Core.Model.User>

<h2>Index</h2>

<ul>
	@foreach (var user in Model)
	{
		<li>@user.Name (@user.EmailAddress)</li>
	}
</ul>

@using(Html.BeginForm("Create", "Home", FormMethod.Post))
{
	<input type="text" name="Name" />
	<input type="text" name="EmailAddress" />
	<input type="submit" value="Submit" />
}